"use strict";
let nvalor;
let svalor;
let uvalor;
uvalor = 10;
nvalor = uvalor;
svalor = uvalor;
svalor += 10;
console.log(uvalor, typeof (uvalor));
console.log(nvalor, typeof (nvalor));
console.log(svalor, typeof (svalor));
svalor = "30";
nvalor = svalor;
console.log(typeof (nvalor), typeof (svalor));
nvalor = Number(svalor);
console.log(typeof (nvalor), typeof (svalor));
svalor = String(nvalor);
console.log(typeof (nvalor), typeof (svalor));
const num = 10;
const str = num.toString(num);
const str2 = String(num);
const str3 = "" + num;
const str4 = `${num}`;
console.log(str, typeof (str));
console.log(str2, typeof (str2));
console.log(str3, typeof (str3));
console.log(str4, typeof (str4));
const str5 = "10.56";
const num5 = Number(str5);
const num6 = parseInt(str5);
const num7 = parseFloat(str5);
const num8 = +str5;
console.log(num5, typeof (num5));
console.log(num6, typeof (num6));
console.log(num7, typeof (num7));
console.log(num8, typeof (num8));
const valor_bool = true;
const string_bool = String(valor_bool);
console.log(string_bool);
